# Generated by Django 5.0.7 on 2024-07-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(default=100)),
                ('start_time', models.FloatField(default=0.0)),
                ('end_time', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='clip',
            name='end_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='clip',
            name='max_volume',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='clip',
            name='start_time',
            field=models.FloatField(default=0.0),
        ),
    ]
