# Generated by Django 5.0.7 on 2024-07-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='order',
            field=models.IntegerField(default=100000),
        ),
    ]
