# Generated by Django 5.0.7 on 2024-07-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0002_clip_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='last_played',
            field=models.BooleanField(default=False),
        ),
    ]
