# Generated by Django 5.0.7 on 2024-07-21 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0002_settings_clip_end_time_clip_max_volume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='start_time',
        ),
    ]
