# Generated by Django 5.0.7 on 2024-07-21 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0003_remove_settings_end_time_remove_settings_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='volume',
            new_name='max_volume',
        ),
    ]
