# Generated by Django 5.0.7 on 2026-04-11 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0005_delete_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=100000)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_clips', to='clips.clip')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_clips', to='clips.playlist')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('playlist', 'clip')},
            },
        ),
    ]
