# Generated by Django 6.0.6 on 2026-06-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadjob',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='downloadjob',
            name='raw_file',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='downloadjob',
            name='end_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='downloadjob',
            name='format_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='downloadjob',
            name='output_format',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='downloadjob',
            name='start_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='downloadjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('fetching', 'Fetching'), ('fetched', 'Fetched'), ('converting', 'Converting'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
