# Generated by Django 5.0.7 on 2024-08-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='location',
            field=models.CharField(default='front_door', max_length=255),
        ),
    ]
