# Generated by Django 5.0.7 on 2024-08-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_alter_track_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
